version: 2.1

jobs:
  gh-cli-tests:
    docker:
      - image: ghcr.io/supportpal/github-gh-cli:2.72.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: setup Github CLI
          command: echo "$GH_TOKEN" > /tmp/gh_token && env -u GH_TOKEN gh auth login --with-token < /tmp/gh_token && rm /tmp/gh_token

workflows:
  gh-cli-tests-workflow: 
    jobs:
      - gh-cli-tests:
          context: vijay-personal
