version: 2.1

jobs:
  gh-cli-tests:
    docker:
      - image: ghcr.io/supportpal/github-gh-cli:2.72.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: setup Github CLI
          command: echo "$GH_RELEASE_PAT" > /tmp/gh_token && env -u GH_TOKEN gh auth login --with-token < /tmp/gh_token && rm /tmp/gh_token
      - run: 
          name: Generate a new release from main
          command: gh release create v0.0.1 --notes "CircleCI Automated Release Creation test" --generate-notes --latest

workflows:
  gh-cli-tests-workflow: 
    jobs:
      - gh-cli-tests
